# Generated by Django 4.0.4 on 2022-05-10 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_index', models.IntegerField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_index', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('power', models.IntegerField(default=0)),
                ('hit_prob', models.IntegerField(default=0)),
                ('pp', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=False)),
                ('flinch_rate', models.IntegerField(default=0)),
                ('min_hits', models.IntegerField(default=1)),
                ('max_hits', models.IntegerField(default=1)),
                ('damage_cls', models.CharField(max_length=20)),
                ('flavor_text', models.TextField()),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.locale')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_index', models.IntegerField(default=-1, verbose_name='도감번호')),
                ('name', models.CharField(max_length=50)),
                ('is_mythical', models.BooleanField(default=False)),
                ('is_legendary', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('hp', models.IntegerField(default=0, verbose_name='체력')),
                ('attack', models.IntegerField(default=0, verbose_name='공격')),
                ('defense', models.IntegerField(default=0, verbose_name='방어')),
                ('spattack', models.IntegerField(default=0, verbose_name='특수공격')),
                ('spdefense', models.IntegerField(default=0, verbose_name='특수방어')),
                ('speed', models.IntegerField(default=0, verbose_name='스피드')),
                ('total', models.IntegerField(default=0, verbose_name='총합')),
                ('evolves_from', models.IntegerField(blank=True, null=True)),
                ('evolves_to', models.IntegerField(blank=True, null=True)),
                ('abilities', models.ManyToManyField(related_name='abilities', to='pokemon.ability')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.locale')),
            ],
        ),
        migrations.CreateModel(
            name='PokeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_index', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=7)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.locale')),
            ],
        ),
        migrations.CreateModel(
            name='PokeMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_way', models.CharField(max_length=20)),
                ('learning_level', models.IntegerField(default=0)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemove', to='pokemon.pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='types', to='pokemon.poketype'),
        ),
        migrations.AddField(
            model_name='ability',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.locale'),
        ),
    ]
